builtin_interfaces/Time stamp

float64[] angles_fr
float64[] angles_fl
float64[] angles_br
float64[] angles_bl

float64[] torques_fr
float64[] torques_fl
float64[] torques_br
float64[] torques_bl

geometry_msgs/Point point_fr
geometry_msgs/Point point_fl
geometry_msgs/Point point_br
geometry_msgs/Point point_bl

geometry_msgs/Vector3 force_fr
geometry_msgs/Vector3 force_fl
geometry_msgs/Vector3 force_br
geometry_msgs/Vector3 force_bl
